###
Author: Peter Peterson
Date: 2017-07-24
Description: Code for interactions with the staging page
Original file: staging.coffee
###

import Shared from './mixins.coffee'
import Vue from 'vue'

generateResultsSet = ()->
  results = []
  for x in [1..100]
    results.push {count:x, filename: Math.random().toString(36).substring(7)}

  return results

stagingComponent = {
  mixins:[Shared.mixin]
  data: ()->
      return
        stagingAllFiles: false
        loading: false
        selectAll: false
        results: []
        selected: []

  created: ()->
    window.staging = @
    console.log "Staging created"
  mounted: ()->
    console.log "Component mounted"
    window.base.bindEvents()
    if localStorage.getItem("stage") is "selectedFiles"
      # Files array is generated by the staging django template
      files = JSON.parse(localStorage.getItem("selectedFiles"))
      for file in files
        @results.push {'selected':false, 'file':file}
    else
      @stagingAllFiles = true
      @loading = true
      query = @stripData()# localStorage.getItem("search")
      new Ajax
        url: "/dal/staging/"
        method: "post"
        accept: "json"
        data: query
        success: (data)=>
          console.log "got this data back from the request"
          console.log data
          @loading = false
        fail: (statusMsg, status, xhr)->
          console.log "ajax failed"


      # call api to start staging process...

  methods:
    toggleAll:()->
      @selectAll = !@selectAll
      if @selectAll
        for file in @results
          file.selected = true
          @selected.push(file)
      else
        for file in @results
          file.selected = false
        @selected = []

    downloadSelected: ()->
      console.log "downloading selected"
    toggleSelected:(item)->
      item.selected = !item.selected
      if item.selected
        @selected.push(item)
      else
        indx = _.indexOf(@selected, item)
        @selected.splice(indx, 1)

}


export default stagingComponent
