# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20160217_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='instrument',
            field=models.CharField(choices=[('mosaic3', 'mosaic3'), ('mop/ice', 'mop/ice'), ('arcon', 'arcon'), ('spartan', 'spartan'), ('decam', 'decam'), ('90prime', '90prime'), ('falmingos', 'falmingos'), ('gtcam', 'gtcam'), ('wildfire', 'wildfire'), ('chiron', 'chiron'), ('osiris', 'osiris'), ('arcoiris', 'arcoiris'), ('andicam', 'andicam'), ('echelle', 'echelle'), ('flamingos', 'flamingos'), ('sam', 'sam'), ('newfirm', 'newfirm'), ('goodman', 'goodman'), ('y4kcam', 'y4kcam'), ('minimo/ice', 'minimo/ice'), ('ice', 'ice'), ('ispi', 'ispi'), ('mosaic', 'mosaic'), ('goodman spectrograph', 'goodman spectrograph'), ('hdi', 'hdi'), ('bench', 'bench'), ('kosmos', 'kosmos'), ('spartan ir camera', 'spartan ir camera'), ('soi', 'soi'), ('(p)odi', '(p)odi'), ('whirc', 'whirc'), ('cosmos', 'cosmos')], default='y4kcam', max_length=20),
            preserve_default=False,
        ),
    ]
