# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_slot_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='emptyslot',
            name='instrument',
            field=models.CharField(default='y4kcam', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='emptyslot',
            unique_together=set([('telescope', 'instrument', 'obsdate')]),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([('telescope', 'instrument', 'obsdate')]),
        ),
        migrations.AlterIndexTogether(
            name='emptyslot',
            index_together=set([('telescope', 'instrument', 'obsdate')]),
        ),
        migrations.AlterIndexTogether(
            name='slot',
            index_together=set([('telescope', 'instrument', 'obsdate')]),
        ),
    ]
