# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20160420_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPropid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescope', models.CharField(max_length=10)),
                ('instrument', models.CharField(max_length=20)),
                ('propids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='slot',
            name='instrument',
            field=models.CharField(choices=[('(p)odi', '(p)odi'), ('90prime', '90prime'), ('andicam', 'andicam'), ('arcoiris', 'arcoiris'), ('arcon', 'arcon'), ('bench', 'bench'), ('biw', 'biw'), ('chiron', 'chiron'), ('cosmos', 'cosmos'), ('decam', 'decam'), ('echelle', 'echelle'), ('falmingos', 'falmingos'), ('flamingos', 'flamingos'), ('goodman', 'goodman'), ('goodman spectrograph', 'goodman spectrograph'), ('gtcam', 'gtcam'), ('hdi', 'hdi'), ('ice', 'ice'), ('ispi', 'ispi'), ('kosmos', 'kosmos'), ('minimo/ice', 'minimo/ice'), ('mop/ice', 'mop/ice'), ('mosaic', 'mosaic'), ('mosaic3', 'mosaic3'), ('newfirm', 'newfirm'), ('osiris', 'osiris'), ('sam', 'sam'), ('soi', 'soi'), ('spartan', 'spartan'), ('spartan ir camera', 'spartan ir camera'), ('whirc', 'whirc'), ('wildfire', 'wildfire'), ('y4kcam', 'y4kcam')], max_length=20),
        ),
    ]
