# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20170509_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpropid',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument'),
        ),
        migrations.AlterField(
            model_name='defaultpropid',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope'),
        ),
        migrations.AlterField(
            model_name='emptyslot',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument'),
        ),
        migrations.AlterField(
            model_name='emptyslot',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope'),
        ),
    ]
