# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20170509_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='split',
            field=models.BooleanField(default=False, help_text='Treat slot as Split Night (hdr propid must be in schedule lists)'),
        ),
    ]
