# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20170918_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='split',
            field=models.BooleanField(default=True, help_text='Iff TRUE treat a slot as Split Night (hdr propid must be in schedule lists)'),
        ),
    ]
