# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2022-01-28 16:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_auto_20220128_0919'),
    ]

    operations = [

        migrations.RunSQL('ALTER TABLE schedule_slot_proposals ALTER COLUMN proposal_id TYPE varchar(20);'),

    ]
