# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='Prefix for Archive Filename', max_length=10)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tada.Instrument')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tada.Site')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tada.Telescope')),
            ],
        ),
    ]
