# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0003_auto_20170216_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprefix',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='obstype',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='proctype',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='prodtype',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
