# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0005_filenamekeywords_floatkeywords_ingestkeywords_ingestrecommendedkeywords_rawkeywords_supportkeywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='HdrFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('definition', models.TextField(help_text='Python function BODY', unique=True)),
            ],
        ),
    ]
