# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0006_hdrfunc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdrfunc',
            name='documentation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
