# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0008_auto_20170301_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdrfunc',
            name='documentation',
            field=models.TextField(blank=True, help_text='Function description.', max_length=160),
        ),
    ]
