# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0010_auto_20170301_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdrfunc',
            name='documentation',
            field=models.TextField(blank=True, help_text='Function description.', max_length=120),
        ),
        migrations.AlterField(
            model_name='hdrfunc',
            name='inkeywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='FITS keywords needed by func', max_length=8), default=list, null=True, size=None),
        ),
    ]
