# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0011_auto_20170301_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstrumentAlias',
        ),
        migrations.RenameField(
            model_name='tacinstrument',
            old_name='name',
            new_name='tac',
        ),
        migrations.AddField(
            model_name='tacinstrument',
            name='hdr',
            field=models.CharField(default='NONE', help_text='Name used in FITS header (keyword=INSTRUME)', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hdrfunc',
            name='inkeywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='FITS keywords needed by func', max_length=8), default=list, size=None),
        ),
    ]
