# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0012_auto_20170301_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacinstrument',
            name='hdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tada.Instrument'),
        ),
    ]
