# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0013_auto_20170301_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacinstrument',
            name='hdr',
        ),
        migrations.AlterField(
            model_name='tacinstrument',
            name='tac',
            field=models.CharField(help_text='Name used by Dave Bells TAC Schedule', max_length=20),
        ),
    ]
