# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0014_auto_20170301_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacInstrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instrument name used by Dave Bells TAC Schedule', max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tacinstrument',
            name='tac',
            field=models.CharField(help_text='Name used by Dave Bells TAC Schedule', max_length=20, unique=True),
        ),
    ]
