# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0018_errorcode_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='id',
        ),
        migrations.RemoveField(
            model_name='telescope',
            name='id',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(help_text='Name used in FITS header (field name INSTRUME)', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='name',
            field=models.CharField(help_text='Name used in FITS header (field name TELES', max_length=10, primary_key=True, serialize=False),
        ),
    ]
