# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0019_auto_20170404_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprefix',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument'),
        ),
        migrations.AlterField(
            model_name='fileprefix',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Site'),
        ),
        migrations.AlterField(
            model_name='fileprefix',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope'),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='Telescope',
        ),
    ]
