# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('natica', '0002_auto_20170502_1328'),
        ('tada', '0020_auto_20170502_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacinstrumentalias',
            name='hdr',
            field=models.ForeignKey(help_text='Name used in FITS header', on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument'),
        ),
        migrations.AlterField(
            model_name='tacinstrumentalias',
            name='tac',
            field=models.CharField(help_text='Name used by Dave Bells TAC Schedule', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tacinstrumentalias',
            unique_together=set([('tac', 'hdr')]),
        ),
    ]
