# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0022_auto_20171010_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacinstrumentalias',
            name='tac',
            field=models.CharField(help_text='Name used by TAC Schedule', max_length=20, primary_key=True, serialize=False),
        ),
    ]
