# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('md5sum', models.CharField(help_text='MD5SUM of FITS file', max_length=40, primary_key=True, serialize=False)),
                ('obsday', models.DateField(help_text='Observation Day')),
                ('telescope', models.CharField(choices=[('aat', 'aat'), ('ct09m', 'ct09m'), ('ct13m', 'ct13m'), ('ct15m', 'ct15m'), ('ct1m', 'ct1m'), ('ct4m', 'ct4m'), ('gem_n', 'gem_n'), ('gem_s', 'gem_s'), ('gemn', 'gemn'), ('gems', 'gems'), ('het', 'het'), ('keckI', 'keckI'), ('keckII', 'keckII'), ('kp09m', 'kp09m'), ('kp13m', 'kp13m'), ('kp21m', 'kp21m'), ('kp4m', 'kp4m'), ('kpcf', 'kpcf'), ('magI', 'magI'), ('magII', 'magII'), ('mmt', 'mmt'), ('soar', 'soar'), ('wiyn', 'wiyn'), ('unknown', 'unknown')], max_length=10)),
                ('instrument', models.CharField(choices=[('mosaic3', 'mosaic3'), ('mop/ice', 'mop/ice'), ('arcon', 'arcon'), ('spartan', 'spartan'), ('decam', 'decam'), ('90prime', '90prime'), ('falmingos', 'falmingos'), ('gtcam', 'gtcam'), ('wildfire', 'wildfire'), ('chiron', 'chiron'), ('osiris', 'osiris'), ('arcoiris', 'arcoiris'), ('andicam', 'andicam'), ('echelle', 'echelle'), ('flamingos', 'flamingos'), ('sam', 'sam'), ('newfirm', 'newfirm'), ('goodman', 'goodman'), ('y4kcam', 'y4kcam'), ('minimo/ice', 'minimo/ice'), ('ice', 'ice'), ('ispi', 'ispi'), ('mosaic', 'mosaic'), ('goodman spectrograph', 'goodman spectrograph'), ('hdi', 'hdi'), ('bench', 'bench'), ('kosmos', 'kosmos'), ('spartan ir camera', 'spartan ir camera'), ('soi', 'soi'), ('(p)odi', '(p)odi'), ('whirc', 'whirc'), ('cosmos', 'cosmos'), ('unknown', 'unknown')], max_length=25)),
                ('srcpath', models.CharField(help_text='Path of file as submitted', max_length=256)),
                ('recorded', models.DateTimeField(default=django.utils.timezone.now, help_text='When SourceFile recorded')),
                ('submitted', models.DateTimeField(help_text='When submitted to archive', null=True)),
                ('success', models.NullBooleanField(help_text='Null until ingest attempted.Then True iff Archive reported success on ingest')),
                ('archerr', models.CharField(blank=True, help_text='Archive ingest error message', max_length=256)),
                ('archfile', models.CharField(blank=True, help_text='Basename of FITS file in Archive', max_length=80)),
            ],
            options={
                'ordering': ('telescope', 'instrument', 'srcpath'),
            },
        ),
    ]
