# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 23:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='sourcefile',
            name='metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(help_text='FITS metadata changed by ingest', null=True),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='obsday',
            field=models.DateField(blank=True, help_text='Observation Day'),
        ),
    ]
