# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_sourcefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcefile',
            options={'ordering': ('recorded',)},
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='when',
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='archerr',
            field=models.CharField(blank=True, help_text='Archive ingest error message', max_length=256),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='archfile',
            field=models.CharField(blank=True, help_text='Basename of FITS file in Archive', max_length=80),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='recorded',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 20, 16, 40, 9, 60356, tzinfo=utc), help_text='When SourceFile recorded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, help_text='When submitted to archive', null=True),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='success',
            field=models.NullBooleanField(help_text='Null until ingest attempted.Then True iff Archive reported success on ingest'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='source',
            field=models.CharField(help_text='Path of file as submitted', max_length=256, primary_key=True, serialize=False),
        ),
    ]
