# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20160420_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='recorded',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When SourceFile recorded'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='submitted',
            field=models.DateTimeField(help_text='When submitted to archive', null=True),
        ),
    ]
