# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20160609_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='errcode',
            field=models.CharField(choices=[('DUPFITS', 'DUPFITS'), ('BADPROP', 'BADPROP'), ('COLLIDE', 'COLLIDE'), ('NOPROP', 'NOPROP'), ('MISSREQ', 'MISSREQ'), ('BADDATE', 'BADDATE'), ('NOFITS', 'NOFITS'), ('UNKNOWN', 'UNKNOWN'), ('none', 'none')], default='none', help_text='Error code for Archive Ingest', max_length=10),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='instrument',
            field=models.CharField(choices=[('arcoiris', 'arcoiris'), ('90prime', '90prime'), ('biw', 'biw'), ('mosaic3', 'mosaic3'), ('(p)odi', '(p)odi'), ('andicam', 'andicam'), ('arcon', 'arcon'), ('bench', 'bench'), ('chiron', 'chiron'), ('cosmos', 'cosmos'), ('decam', 'decam'), ('echelle', 'echelle'), ('falmingos', 'falmingos'), ('flamingos', 'flamingos'), ('goodman', 'goodman'), ('goodman spectrograph', 'goodman spectrograph'), ('gtcam', 'gtcam'), ('hdi', 'hdi'), ('ice', 'ice'), ('ispi', 'ispi'), ('kosmos', 'kosmos'), ('minimo/ice', 'minimo/ice'), ('mop/ice', 'mop/ice'), ('mosaic', 'mosaic'), ('newfirm', 'newfirm'), ('osiris', 'osiris'), ('sam', 'sam'), ('soi', 'soi'), ('spartan', 'spartan'), ('spartan ir camera', 'spartan ir camera'), ('unknown', 'unknown'), ('whirc', 'whirc'), ('wildfire', 'wildfire'), ('y4kcam', 'y4kcam')], max_length=25),
        ),
    ]
