# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 18:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20160620_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('md5sum', models.CharField(help_text='MD5SUM of FITS file', max_length=40, primary_key=True, serialize=False)),
                ('obsday', models.DateField(help_text='Observation Day', null=True)),
                ('telescope', models.CharField(choices=[('aat', 'aat'), ('ct09m', 'ct09m'), ('ct13m', 'ct13m'), ('ct15m', 'ct15m'), ('ct1m', 'ct1m'), ('ct4m', 'ct4m'), ('gem_n', 'gem_n'), ('gem_s', 'gem_s'), ('gemn', 'gemn'), ('gems', 'gems'), ('het', 'het'), ('keckI', 'keckI'), ('keckII', 'keckII'), ('kp09m', 'kp09m'), ('kp13m', 'kp13m'), ('kp21m', 'kp21m'), ('kp4m', 'kp4m'), ('kpcf', 'kpcf'), ('magI', 'magI'), ('magII', 'magII'), ('mmt', 'mmt'), ('soar', 'soar'), ('wiyn', 'wiyn'), ('unknown', 'unknown')], max_length=10)),
                ('instrument', models.CharField(choices=[('arcoiris', 'arcoiris'), ('90prime', '90prime'), ('biw', 'biw'), ('mosaic3', 'mosaic3'), ('(p)odi', '(p)odi'), ('andicam', 'andicam'), ('arcon', 'arcon'), ('bench', 'bench'), ('chiron', 'chiron'), ('cosmos', 'cosmos'), ('decam', 'decam'), ('echelle', 'echelle'), ('falmingos', 'falmingos'), ('flamingos', 'flamingos'), ('goodman', 'goodman'), ('goodman spectrograph', 'goodman spectrograph'), ('gtcam', 'gtcam'), ('hdi', 'hdi'), ('ice', 'ice'), ('ispi', 'ispi'), ('kosmos', 'kosmos'), ('minimo/ice', 'minimo/ice'), ('mop/ice', 'mop/ice'), ('mosaic', 'mosaic'), ('newfirm', 'newfirm'), ('osiris', 'osiris'), ('sam', 'sam'), ('soi', 'soi'), ('spartan', 'spartan'), ('spartan ir camera', 'spartan ir camera'), ('unknown', 'unknown'), ('whirc', 'whirc'), ('wildfire', 'wildfire'), ('y4kcam', 'y4kcam')], max_length=25)),
                ('srcpath', models.CharField(help_text='Path of file as submitted', max_length=256)),
                ('recorded', models.DateTimeField(default=django.utils.timezone.now, help_text='When AuditRecord recorded')),
                ('submitted', models.DateTimeField(help_text='When submitted to archive', null=True)),
                ('success', models.NullBooleanField(help_text='Null until ingest attempted.Then True iff Archive reported success on ingest')),
                ('archerr', models.CharField(blank=True, help_text='Archive ingest error message', max_length=256)),
                ('errcode', models.CharField(choices=[('DUPFITS', 'DUPFITS'), ('BADPROP', 'BADPROP'), ('COLLIDE', 'COLLIDE'), ('NOPROP', 'NOPROP'), ('MISSREQ', 'MISSREQ'), ('BADDATE', 'BADDATE'), ('NOFITS', 'NOFITS'), ('UNKNOWN', 'UNKNOWN'), ('none', 'none')], default='none', help_text='Error code for Archive Ingest', max_length=10)),
                ('archfile', models.CharField(blank=True, help_text='Basename of FITS file in Archive', max_length=80)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField(help_text='FITS metadata changed by ingest', null=True)),
                ('staged', models.BooleanField(default=False, help_text='Marked for subsequent action.')),
            ],
            options={
                'ordering': ('telescope', 'instrument', 'srcpath'),
            },
        ),
        migrations.DeleteModel(
            name='SourceFile',
        ),
    ]
