# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auto_20160621_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='dome_host',
            field=models.CharField(blank=True, help_text='Host name of Dome that created FITS', max_length=40),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='mtn_host',
            field=models.CharField(blank=True, help_text='Host name of Mountain that received FITS', max_length=40),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='valley_host',
            field=models.CharField(blank=True, help_text='Host name of Mountain that received FITS', max_length=40),
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='instrument',
            field=models.CharField(choices=[('arcoiris', 'arcoiris'), ('90prime', '90prime'), ('mosaic3', 'mosaic3'), ('ccd_imager', 'ccd_imager'), ('(p)odi', '(p)odi'), ('andicam', 'andicam'), ('arcon', 'arcon'), ('bench', 'bench'), ('chiron', 'chiron'), ('cosmos', 'cosmos'), ('decam', 'decam'), ('echelle', 'echelle'), ('falmingos', 'falmingos'), ('flamingos', 'flamingos'), ('goodman', 'goodman'), ('goodman spectrograph', 'goodman spectrograph'), ('gtcam', 'gtcam'), ('hdi', 'hdi'), ('ice', 'ice'), ('ispi', 'ispi'), ('kosmos', 'kosmos'), ('minimo/ice', 'minimo/ice'), ('mop/ice', 'mop/ice'), ('mosaic', 'mosaic'), ('newfirm', 'newfirm'), ('osiris', 'osiris'), ('sam', 'sam'), ('soi', 'soi'), ('spartan', 'spartan'), ('spartan ir camera', 'spartan ir camera'), ('unknown', 'unknown'), ('whirc', 'whirc'), ('wildfire', 'wildfire'), ('y4kcam', 'y4kcam')], max_length=25),
        ),
    ]
