# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20160629_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditrecord',
            old_name='mtn_host',
            new_name='mountain_host',
        ),
    ]
