# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_auto_20160629_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='fstop',
            field=models.CharField(blank=True, help_text='Most downstream stop of FITS file', max_length=25),
        ),
    ]
