# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_auditrecord_fstop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditrecord',
            options={},
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='fstop',
            field=models.CharField(blank=True, choices=[('dome', 'dome'), ('mountain:dropbox', 'mountain:dropbox'), ('mountain:queue', 'mountain:queue'), ('mountain:cache', 'mountain:cache'), ('mountain:anticache`', 'mountain:anticache`'), ('valley:dropbox', 'valley:dropbox'), ('valley:queue', 'valley:queue'), ('valley:cache', 'valley:cache'), ('valley:anticache', 'valley:anticache'), ('archive', 'archive')], help_text='Most downstream stop of FITS file', max_length=25),
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='md5sum',
            field=models.CharField(db_index=True, help_text='MD5SUM of FITS file', max_length=40, primary_key=True, serialize=False),
        ),
    ]
