# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_auto_20160809_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditrecord',
            old_name='recorded',
            new_name='updated',
        ),
    ]
