# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 17:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_auto_20160809_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='FITS metadata changed by ingest', null=True),
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='submitted',
            field=models.DateTimeField(blank=True, help_text='When submitted to archive', null=True),
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When AuditRecord updated'),
        ),
    ]
