# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_auto_20160809_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='hide',
            field=models.BooleanField(default=False, help_text='Exclude these records in audit reports.'),
        ),
    ]
