# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_auditrecord_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='fstop_host',
            field=models.CharField(blank=True, help_text='Host name of more recent fstop', max_length=40),
        ),
    ]
