# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0016_auto_20160920_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='telescope',
            field=models.CharField(choices=[('bok23m', 'bok23m'), ('aat', 'aat'), ('ct09m', 'ct09m'), ('ct13m', 'ct13m'), ('ct15m', 'ct15m'), ('ct1m', 'ct1m'), ('ct4m', 'ct4m'), ('gem_n', 'gem_n'), ('gem_s', 'gem_s'), ('gemn', 'gemn'), ('gems', 'gems'), ('het', 'het'), ('keckI', 'keckI'), ('keckII', 'keckII'), ('kp09m', 'kp09m'), ('kp13m', 'kp13m'), ('kp21m', 'kp21m'), ('kp4m', 'kp4m'), ('kpcf', 'kpcf'), ('magI', 'magI'), ('magII', 'magII'), ('mmt', 'mmt'), ('soar', 'soar'), ('wiyn', 'wiyn'), ('unknown', 'unknown')], max_length=10),
        ),
    ]
