# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0016_auto_20160920_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='instrument',
            field=models.CharField(choices=[('arcoiris', 'arcoiris'), ('whirc', 'whirc'), ('decam', 'decam'), ('90prime', '90prime'), ('goodman', 'goodman'), ('spartan', 'spartan'), ('echelle', 'echelle'), ('flamingos', 'flamingos'), ('ice', 'ice'), ('chiron', 'chiron'), ('cosmos', 'cosmos'), ('newfirm', 'newfirm'), ('y4kcam', 'y4kcam'), ('falmingos', 'falmingos'), ('wildfire', 'wildfire'), ('mosaic', 'mosaic'), ('osiris', 'osiris'), ('soi', 'soi'), ('sami', 'sami'), ('ispi', 'ispi'), ('gtcam', 'gtcam'), ('ccd_imager', 'ccd_imager'), ('goodman spectrograph', 'goodman spectrograph'), ('bench', 'bench'), ('andicam', 'andicam'), ('(p)odi', '(p)odi'), ('kosmos', 'kosmos'), ('spartan ir camera', 'spartan ir camera'), ('arcon', 'arcon'), ('hdi', 'hdi'), ('mop/ice', 'mop/ice'), ('minimo/ice', 'minimo/ice'), ('mosaic3', 'mosaic3'), ('foo', 'foo'), ('TESTinstrument', 'TESTinstrument')], max_length=25),
        ),
        migrations.AlterField(
            model_name='auditrecord',
            name='telescope',
            field=models.CharField(choices=[('ct15m', 'ct15m'), ('bok23m', 'bok23m'), ('ct13m', 'ct13m'), ('ct4m', 'ct4m'), ('kp4m', 'kp4m'), ('kp09m', 'kp09m'), ('ct09m', 'ct09m'), ('kpcf', 'kpcf'), ('ctlab', 'ctlab'), ('ct1m', 'ct1m'), ('wiyn', 'wiyn'), ('soar', 'soar'), ('kp35m', 'kp35m'), ('kp21m', 'kp21m'), ('TESTtele', 'TESTtele')], max_length=10),
        ),
    ]
