# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_auto_20170404_1458'),
        ('audit', '0017_auto_20170406_0945'),
    ]

    operations = [
    ]
