# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0020_merge_20170417_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tada.Telescope'),
        ),
    ]
