prefix = '[{"prefix": "psg"}, {"prefix": "psg"}, {"prefix": "pso"}, {"prefix": "psi"}, {"prefix": "pss"}, {"prefix": "pss"}, {"prefix": "psa"}, {"prefix": "c4d"}, {"prefix": "c4c"}, {"prefix": "c4i"}, {"prefix": "c4m"}, {"prefix": "c4n"}, {"prefix": "c4ai"}, {"prefix": "c15e"}, {"prefix": "c15e"}, {"prefix": "c15s"}, {"prefix": "c13a"}, {"prefix": "c1i"}, {"prefix": "c09i"}, {"prefix": "clc"}, {"prefix": "k4m"}, {"prefix": "k4m"}, {"prefix": "k4n"}, {"prefix": "k4k"}, {"prefix": "k4k"}, {"prefix": "k4i"}, {"prefix": "k4w"}, {"prefix": "k4f"}, {"prefix": "kww"}, {"prefix": "kww"}, {"prefix": "kwb"}, {"prefix": "kwi"}, {"prefix": "kwo"}, {"prefix": "k21i"}, {"prefix": "k21w"}, {"prefix": "k21f"}, {"prefix": "k21g"}, {"prefix": "kcfs"}, {"prefix": "k09h"}, {"prefix": "k09m"}, {"prefix": "k09i"}, {"prefix": "ksb"}, {"prefix": "ksb"}]'

obstype = '[{"name": "zero", "code": "z"}, {"name": "object", "code": "o"}, {"name": "photometric standard", "code": "p"}, {"name": "bias", "code": "z"}, {"name": "dome or projector flat", "code": "f"}, {"name": "dome flat", "code": "f"}, {"name": "dflat", "code": "f"}, {"name": "flat", "code": "f"}, {"name": "projector", "code": "f"}, {"name": "sky", "code": "s"}, {"name": "skyflat", "code": "s"}, {"name": "dark", "code": "d"}, {"name": "calibration", "code": "c"}, {"name": "calibration or comparison", "code": "c"}, {"name": "comp", "code": "c"}, {"name": "comparison", "code": "c"}, {"name": "illumination calibration", "code": "i"}, {"name": "focus", "code": "g"}, {"name": "fringe", "code": "h"}, {"name": "pupil", "code": "r"}, {"name": "nota", "code": "u"}]'

proctype = '[{"name": "raw", "code": "r"}, {"name": "instcal", "code": "o"}, {"name": "mastercal", "code": "c"}, {"name": "projected", "code": "p"}, {"name": "stacked", "code": "s"}, {"name": "skysub", "code": "k"}, {"name": "nota", "code": "u"}]'

prodtype = '[{"name": "image", "code": "i"}, {"name": "image 2nd version 1", "code": "j"}, {"name": "dqmask", "code": "d"}, {"name": "expmap", "code": "e"}, {"name": "graphics (size)", "code": "g"}, {"name": "weight", "code": "w"}, {"name": "nota", "code": "u"}, {"name": "wtmap", "code": "-"}, {"name": "resampled", "code": "-"}]'

rawreq = '[{"name": "TELESCOP", "comment": ""}]'

filenamereq = '[{"name": "DATE-OBS", "comment": "triplespec doesn\'t have it; comes from other field"}, {"name": "DTSITE", "comment": "for BASENAME"}, {"name": "DTTELESC", "comment": "for BASENAME"}, {"name": "DTINSTRU", "comment": "for BASENAME"}, {"name": "OBSTYPE", "comment": "for BASENAME"}, {"name": "PROCTYPE", "comment": "for BASENAME"}, {"name": "PRODTYPE", "comment": "for BASENAME"}, {"name": "DTCALDAT", "comment": "for PATH (dome)"}, {"name": "DTPROPID", "comment": "for PATH (dome)"}]'

ingestreq = '[{"name": "SIMPLE", "comment": ""}, {"name": "OBSERVAT", "comment": "needed for std filename"}, {"name": "DTPROPID", "comment": "observing proposal ID"}, {"name": "DTCALDAT", "comment": "calendar date from observing schedule"}, {"name": "DTACQNAM", "comment": "file name supplied at telescope; User knows on THIS name."}, {"name": "DTNSANAM", "comment": "file name in archive (renamed from user supplied)"}, {"name": "DTTELESC", "comment": ""}, {"name": "DTSITE", "comment": ""}, {"name": "DTINSTRU", "comment": ""}]'

ingestrec = '[{"name": "INSTRUME", "comment": "moved from RAW_REQUIRED to statisfy: /scraped/mtn_raw/ct15m-echelle/chi150724.10"}, {"name": "DTCOPYRI", "comment": "coypright holder of data"}, {"name": "DTOBSERV", "comment": ""}, {"name": "DTPI", "comment": ""}, {"name": "DTPIAFFL", "comment": ""}, {"name": "DTTITLE", "comment": ""}, {"name": "OBSID", "comment": ""}, {"name": "DTACQNAM", "comment": ""}, {"name": "DTCALDAT", "comment": ""}, {"name": "DTINSTRU", "comment": ""}, {"name": "DTNSANAM", "comment": ""}, {"name": "DTPROPID", "comment": ""}, {"name": "DTSITE", "comment": ""}, {"name": "DTTELESC", "comment": ""}, {"name": "PROCTYPE", "comment": ""}, {"name": "PRODTYPE", "comment": ""}]'

supportreq = '[{"name": "IMAGETYP", "comment": ""}, {"name": "DATE-OBS", "comment": ""}, {"name": "TIME-OBS", "comment": ""}, {"name": "DATE", "comment": ""}, {"name": "PROPID", "comment": ""}]'

floatreq = '[{"name": "DATAMAX", "comment": ""}, {"name": "DATAMIN", "comment": ""}, {"name": "PSCAL", "comment": ""}, {"name": "PZERO", "comment": ""}, {"name": "TSCAL", "comment": ""}, {"name": "TZERO", "comment": ""}, {"name": "CRPIX", "comment": ""}, {"name": "CRVAL", "comment": ""}, {"name": "CDELT", "comment": ""}, {"name": "CROTA", "comment": ""}, {"name": "PC", "comment": ""}, {"name": "CD", "comment": ""}, {"name": "PV", "comment": ""}, {"name": "CRDER", "comment": ""}, {"name": "CSYER", "comment": ""}, {"name": "EPOCH", "comment": ""}, {"name": "EQUINOX", "comment": ""}, {"name": "MJD-OBS", "comment": ""}, {"name": "MJD-AVG", "comment": ""}, {"name": "LONPOLE", "comment": ""}, {"name": "LATPOLE", "comment": ""}, {"name": "OBSGEO-Z", "comment": ""}, {"name": "OBSGEO-Y", "comment": ""}, {"name": "OBSGEO-X", "comment": ""}, {"name": "RESTFRQ", "comment": ""}, {"name": "RESTWAV", "comment": ""}, {"name": "VELANGL", "comment": ""}, {"name": "VELOSYS", "comment": ""}, {"name": "ZSOURCE", "comment": ""}]'
