# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('name', models.CharField(help_text='Name used in FITS header (field name INSTRUME)', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Site (mountain)', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('name', models.CharField(help_text='Name used in FITS header (field name TELES', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
