# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='Site (mountain)', max_length=10, primary_key=True, serialize=False),
        ),
    ]
