from django import forms
from .models import VoiSiap

class VoiSiapForm(forms.ModelForm):
    class Meta:
        model = VoiSiap
        fields = [
            'reference',
            'fits_extension',   
            'object',           
            'survey',           
            'surveyid',         
            'prop_id',          
            'start_date',       
            'ra',               
            'dec',              
            'equinox',          
            'naxes',            
            'naxis_length',     
            'instrument',       
            'telescope',        
            'filesize',         
            'pixflags',         
            'bandpass_id',      
            'bandpass_unit',    
            'bandpass_lolimit', 
            'bandpass_hilimit', 
            'exposure',         
            'depth',            
            'depth_err',        
            'magzero',          
            'magerr',           
            'seeing',           
            'release_date',     
            'noao_id',          
            'vo_id',            
            'airmass',          
            'astrmcat',         
            'biasfil',          
            'bunit',            
            'dqmask',           
            'darkfil',          
            'date_obs',         
            'flatfil',          
            'ds_ident',         
            'dtnsanam',         
            'dtacqnam',         
            'dtobserv',         
            'dtpi',             
            'dtpiaffl',         
            'dtpropid',         
            'dtsite',           
            'dttitle',          
            'dtutc',            
            'efftime',          
            'filter',           
            'filtid',           
            'frngfil',          
            'ha',               
            'instrume',         
            'md5sum',           
            'mjd_obs',          
            'obs_elev',         
            'obs_lat',          
            'obs_long',         
            'photbw',           
            'photclam',         
            'photfwhm',         
            'pipeline',         
            'plver',            
            'proctype',         
            'prodtype',         
            'puplfil',          
            'radesys',          
            'rawfile',          
            'sb_recno',         
            'sflatfil',         
            'timesys',          
            'disper',           
            'obsmode',          
            'filename',         
            'nocslit',          
            'nocssn',           
            'zd',               
            'rspgrp',           
            'rsptgrp',          
            'reject',           
            'seqid',            
            'plqname',          
            'pldname',          
            ]


