# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=2, unique=True)),
                ('telescope', models.CharField(help_text='Name used in FITS header (field name TELES', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tac', models.CharField(help_text='Name used by Dave Bells TAC Schedule', max_length=20, unique=True)),
                ('fits', models.CharField(help_text='Name used in FITS header (field name INSTRUME)', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits', models.CharField(help_text='Name used in FITS header (field name TELESCOP)', max_length=10, unique=True)),
            ],
        ),
    ]
