# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Telescope',
        ),
        migrations.AddField(
            model_name='fileprefix',
            name='instrument',
            field=models.CharField(default='NA', help_text='Name used in FITS header (field name INSTRUME)', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileprefix',
            name='prefix',
            field=models.CharField(default='unknown', help_text='Prefix for Archive Filename', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileprefix',
            name='tacinst',
            field=models.CharField(default='unknown', help_text='Name used by Dave Bells TAC Schedule', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileprefix',
            name='site',
            field=models.CharField(help_text='Site (mountain)', max_length=2),
        ),
        migrations.AlterField(
            model_name='fileprefix',
            name='telescope',
            field=models.CharField(help_text='Name used in FITS header (field name TELES', max_length=10),
        ),
    ]
