# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_auto_20160614_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprefix',
            name='site',
            field=models.CharField(help_text='Site (mountain)', max_length=10),
        ),
    ]
