# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_auto_20160614_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprefix',
            name='prefix',
            field=models.CharField(help_text='Prefix for Archive Filename', max_length=10),
        ),
    ]
