# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_auto_20160615_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprefix',
            name='instrument',
            field=models.CharField(help_text='Name used in FITS header (field name INSTRUME)', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileprefix',
            name='tacinst',
            field=models.CharField(help_text='Name used by Dave Bells TAC Schedule', max_length=20),
        ),
    ]
